project:
  name: greenplus
  tz: America/Asuncion
  adrFolder: ./docs/adr
  packages:
    - name: frontend
      path: ./frontend
      adrFolder: ./frontend/docs/adr
    - name: backend
      path: ./backend
      adrFolder: ./backend/docs/adr
